[env]
#TERM = "gruvbox_dark"

[window]
decorations = "buttonless"
dynamic_padding = true 
#opacity = 0.425
opacity = 1.0
blur = false 
startup_mode = "Windowed" 
title = "bxshan"

padding = { x = 3, y = 3 }

dimensions = { columns = 100, lines = 40 } 

[scrolling]
history = 100000

[font]
size = 20.0

normal = { family = "FiraCode Nerd Font"}

[cursor]
style = { shape = "Block", blinking = "Never" }

[mouse]
hide_when_typing = true

[general]
live_config_reload = true
import = [
  "~/.config/alacritty/themes/themes/gruvbox_dark.toml",
]
